project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Rachel Brody"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Wildlands.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: false
    page-layout: full

editor: visual

