project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Rachel Brody"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Interships
      - href: Wildlands.qmd
        text: Wildlands Field Studies Program
      - href: otherskills.qmd
        text: Other Skills
page-footer:
    left: Updated June 5, 2024
format:
  html:
    mainfont: Cormorant
    theme: styles.scss
    toc: false
    page-layout: full

editor: visual

