---
title: "Internships"
---
LTER Laboratory Technician (April 2023-December 2023)

My primary task was to identify and tag organisms in underwater photos of slates at various long-term research sites in the Santa Barbara Channel. The aim of the project was to track ecological change in the marine environment over time.




Nursery Intern at the Southern African Foundation for the Conservation of Coastal Birds (January 2020-March 2020)

I raised African penguin chicks that had been abandoned or hurt. Daily tasks included preparing food, feeding, cleaning, helping with vet checks, giving medication, and generally monitoring health and behavior. I worked primarily alone in the nursery. The hardest part was to not coddle the adorable chicks because that would reduce their chances of being able to survive in the wild.





Songbird Intern at the Santa Barbara Wildlife Care Network

I learned so much from working alongside long time bird rehabilitators. I helped feed, give medication, and clean enclosures for wounded or sick birds.





